name: "cross-tests"

inputs:
  rust:
    required: true
  package:
    required: true
  target:
    required: true
  features:
    required: true

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ inputs.rust }}
          targets: ${{ inputs.target }}
      - uses: RustCrypto/actions/cross-install@master
      - run: |
          # cd ${{ inputs.package }} Not needed, as only a single crate is located in this repository
          cross test --target ${{ inputs.target }} --no-default-features \
            --features ${{ inputs.features }}
        shell: bash
