stages:
  - lint
  - build

fmt:
  stage: lint
  image: rust:latest
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt --version
    - cargo fmt --all -- --check
  tags:
    - asprunner

clippy:
  stage: lint
  image: rust:latest
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy --version
    - cargo clippy --all-targets --all-features -- -D warnings
  tags:
    - asprunner

check-for-todos:
  stage: lint
  image: rust:latest
  script:
    - make check-for-todos
  artifacts:
    when: always
    reports:
    paths:
      - ./check_for_todos_results.txt
    expire_in: 2 week
  allow_failure: true
  tags:
    - asprunner

msrv:
  stage: lint
  image: rust:latest
  before_script:
    - cargo install cargo-msrv
  script:
    - make check-msrv
    - cargo msrv verify
  allow_failure: true
  tags:
    - asprunner

default-latest:
  stage: build
  image: rust:latest
  script:
    - rustc --version
    - rustup target add riscv32imac-unknown-none-elf
    - cargo build --verbose
    - cargo build --target riscv32imac-unknown-none-elf --no-default-features
    - cargo test --verbose
  tags:
    - asprunner

default-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - rustc --version
    - rustup target add riscv32imac-unknown-none-elf
    - cargo build --verbose
    - cargo build --verbose --target riscv32imac-unknown-none-elf --no-default-features
    - cargo test --verbose
  allow_failure: true
  tags:
    - asprunner

feature-latest:
  stage: build
  image: rust:latest
  script:
    - rustc --version
    - rustup target add riscv32imac-unknown-none-elf
    - MAX_HASH_OPTIMIZATIONS=10 THREADS=2 cargo build --features fast_verify --verbose
    - MAX_HASH_OPTIMIZATIONS=10 cargo build --features fast_verify --verbose --target riscv32imac-unknown-none-elf --no-default-features
    - MAX_HASH_OPTIMIZATIONS=10 cargo test --features fast_verify --verbose
  tags:
    - asprunner

feature-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - rustc --version
    - rustup target add riscv32imac-unknown-none-elf
    - MAX_HASH_OPTIMIZATIONS=10 THREADS=2 cargo build --features fast_verify --verbose
    - MAX_HASH_OPTIMIZATIONS=10 cargo build --features fast_verify --verbose --target riscv32imac-unknown-none-elf --no-default-features
    - MAX_HASH_OPTIMIZATIONS=10 cargo test --features fast_verify --verbose
  allow_failure: true
  tags:
    - asprunner
